# -*- coding: utf-8 -*-
"""check_images.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KQumaHLS4DanDEzziYUI_FDRR-LoE6wh
"""

#mounting drive 
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
import numpy as np
from sklearn.metrics import mean_squared_error

predicted_images_real_10 = np.load('/content/drive/My Drive/Thesis_code/thesis_data/predicted_images_20/real100.npy')
predicted_images_10 = np.load('/content/drive/My Drive/Thesis_code/thesis_data/predicted_images_20/100.npy')

print(np.min(predicted_images_10), np.max(predicted_images_10))
print(np.min(predicted_images_real_10), np.max(predicted_images_real_10))

print(predicted_images_real_10.dtype)
print(predicted_images_10.dtype)
predicted_images_10 = (predicted_images_10 *127.5 + 127.5).astype(int)
predicted_images_real_10 = (predicted_images_real_10 *127.5 + 127.5).astype(int)

print(predicted_images_real_10.dtype)
print(predicted_images_10.dtype)

print(np.min(predicted_images_10), np.max(predicted_images_10))
print(np.min(predicted_images_real_10), np.max(predicted_images_real_10))

print(predicted_images_10.shape)
print(predicted_images_real_10.shape)

plt.imshow(predicted_images_10[18])

plt.imshow(predicted_images_real_10[18])

